# Generated by Django 5.1.7 on 2025-05-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ljaysApp', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
