# Generated by Django 5.1.7 on 2025-05-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ljaysApp', '0012_remove_transaction_total_quantity_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
