# Generated by Django 5.1.7 on 2025-05-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ljaysApp', '0010_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='items',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='package_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Preparing', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.ManyToManyField(to='ljaysApp.item'),
        ),
    ]
