# Generated by Django 5.1.7 on 2025-05-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ljaysApp', '0011_remove_item_category_transaction_total_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('main_dish', 'Main Dish'), ('rice', 'Rice'), ('beverage', 'Beverage')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='items',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='package_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='Preparing', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
