# Generated by Django 5.1.7 on 2025-05-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ljaysApp', '0007_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
