# Generated by Django 5.1.7 on 2025-04-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ljaysApp', '0004_rename_date_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='preparing', max_length=20),
        ),
    ]
